version: '2.2'
services:
  node:
    build: ./node
    ports:
     - "80:8181"
    depends_on:
     - mysql
    environment:
     - MYSQL_HOST=localhost
     - MYSQL_USER=client
     - MYSQL_PASS=admin
     - MYSQL_DB=node-mysql
     - PORT=80
    volumes:
     - ./node:/app
  mysql:
    build: ./mysql