name: integration
on: [push, pull_request]
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: npm install
      - name: Start
        run: docker-compose up -d