name: integration
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js v10
        uses: actions/setup-node@v1
        with:
          node-version: latest
      - name: Install
        run: npm install
      - name: Start
        run: docker-compose up --exit-code-from App